### ISSUE TITLE
This entity is no longer being provided by the astroweather integration.

### ISSUE THREAD

**Issue by BaltasarParreira** [mawinkler/astroweather#27]
Recently in one or two days I started getting this error for the following entities:

sensor.astroweather_10m_wind_speed
sensor.astroweather_10m_wind_speed_plain
weather.astroweather_38_731_9_1373

Because of this my custom:astroweather-card stopeed working and it only show this:

![image](https://user-images.githubusercontent.com/1650425/226431850-2a9367dd-4508-4769-964f-6fd751332486.png)

this is the code I'm using on the card itself:

```
type: custom:vertical-stack-in-card
title: Weather
cards:
  - type: custom:astroweather-card
    entity: weather.forecast_home
    number_of_forecasts: '5'
    details: false
    deepskydetails: false
    forecast: false
    graph: false
```
