### ISSUE TITLE
Template requires quotes for the time

### ISSUE THREAD

**Issue by mikewagnercmp** [mawinkler/astroweather#45]
Hello, 
My image was not always updating, I did a little googling, and other template examples I saw had quotes around the time frame like shown below - I am not sure either way as I am not a HA expert, but, when i did this, my image started reliably updating, rather than only when i reloaded HA.

```
template:
  - trigger:
    - platform: time_pattern
      # This will update every ten minutes
      minutes: "/10"
  - image:
    - name: UpTonight
      url: http://192.168.1.16:8123/local/uptonight-plot.png
```

**Comment by mawinkler** [comment]
Actually not. Even Home Assistant itself doesn't use quotes in this case.

In general, you don't need quotes.
- Use quotes to force a string, e.g. if your key or value is 10 but you want it to return a String and not a Fixnum, write '10' or "10".
- Use quotes if your value includes special characters, (e.g. :, {, }, [, ], ,, &, *, #, ?, |, -, <, >, =, !, %, @, \).
- Single quotes let you put almost any character in your string, and won't try to parse escape codes. '\n' would be returned as the string \n.
- Double quotes parse escape codes. "\n" would be returned as a line feed character.
- The exclamation mark introduces a method, e.g. !include.

`/` is not a special character.

Example of a generated automation by Home Assistant:

```yaml
- id: '1701330965636'
  alias: huhu
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /10
  condition: []
  action:
  - service: notify.telegram
    data:
      message: huhu
  mode: single
```
