### ISSUE TITLE
EU date

### ISSUE THREAD

**Issue by Trzinka** [mawinkler/astroweather#6]
Hi guys. 
I would like to ask you how to change the date display from US to EU standard? 

Thanks.

**Comment by mawinkler** [comment]
Hi Trzinka,

I think the easiest, for now, would be to use a template sensor for this.

Example:

```yaml
template:
  - sensor:
      - name: "Moon Next Rising"
        state: "{{ as_timestamp(states('sensor.astroweather_moon_next_rising')) | timestamp_custom('%A %B %-d, %H:%M') }}"
        icon: "mdi:calendar-clock"
```

Converts

```
2022-01-14 13:42:41
```

to

```
Friday January 14, 13:42
```

You can freely customize it to your liking.

Official documentation here:
[Time & Date](https://www.home-assistant.io/integrations/time_date/)
