### ISSUE TITLE
Integration not available after installation via HACS

### ISSUE THREAD

**Issue by nohn** [mawinkler/astroweather#65]
I am running Home Assistant Core 2024.12.3 / Frontend 20241127.8 using the official Docker image. I installed AstroWeather 0.70.2 via HACS and restarted Home Assistant (both via the frontend as well by restarting the Container).

The log displays no errors or warnings related to AstroWeather (except the expected one about it being a custom integration).

However, AstroWeather is not available in Settings => Integrations.

A Browser caching issue can be ruled out.

I have seen similar issues that seem to have magically resolved by themselves:
- https://github.com/mawinkler/astroweather/issues/20
- https://github.com/mawinkler/astroweather/issues/3
- https://github.com/mawinkler/astroweather/issues/1

**Comment by mawinkler** [comment]
Have you tried enabling debug mode?
```yaml
logger:
  default: warning
  logs:
    custom_components.astroweather: debug
    pyastroweatherio: debug
```
